<a href="https://colab.research.google.com/github/princejaiswal19/Machine-Learning/blob/main/MLvid1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas


In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
df=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(df);


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
x=np.full((5,4),5)
print(x)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
p=np.eye(4)
print(p)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
b=np.random.random((3,4))
print(b)

[[0.15049489 0.19773733 0.69958216 0.14104336]
 [0.28680474 0.44983649 0.42448572 0.78712126]
 [0.77829566 0.55766786 0.03199404 0.87898565]]


In [ ]:
b=np.random.randint(10,100,(3,5))
print(b)

[[41 50 47 33 94]
 [44 28 18 78 68]
 [63 45 13 88 59]]


In [ ]:
 import pandas as pd


In [ ]:
df= pd.read_csv("http://lib.stat.cmu.edu/datasets/boston", sep="\s+", skiprows=22)

In [ ]:
df.head()

0.00632  18.00  2.310    0  0.5380  6.5750  65.20  4.0900    1  296.0  \
0  396.90000   4.98  24.00  NaN     NaN     NaN    NaN     NaN  NaN    NaN   
1    0.02731   0.00   7.07  0.0   0.469   6.421   78.9  4.9671  2.0  242.0   
2  396.90000   9.14  21.60  NaN     NaN     NaN    NaN     NaN  NaN    NaN   
3    0.02729   0.00   7.07  0.0   0.469   7.185   61.1  4.9671  2.0  242.0   
4  392.83000   4.03  34.70  NaN     NaN     NaN    NaN     NaN  NaN    NaN   

   15.30  
0    NaN  
1   17.8  
2    NaN  
3   17.8  
4    NaN

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
print(df)

        0.00632  18.00  2.310    0  0.5380  6.5750  65.20  4.0900    1  296.0  \
0     396.90000   4.98  24.00  NaN     NaN     NaN    NaN     NaN  NaN    NaN   
1       0.02731   0.00   7.07  0.0   0.469   6.421   78.9  4.9671  2.0  242.0   
2     396.90000   9.14  21.60  NaN     NaN     NaN    NaN     NaN  NaN    NaN   
3       0.02729   0.00   7.07  0.0   0.469   7.185   61.1  4.9671  2.0  242.0   
4     392.83000   4.03  34.70  NaN     NaN     NaN    NaN     NaN  NaN    NaN   
...         ...    ...    ...  ...     ...     ...    ...     ...  ...    ...   
1006  396.90000   5.64  23.90  NaN     NaN     NaN    NaN     NaN  NaN    NaN   
1007    0.10959   0.00  11.93  0.0   0.573   6.794   89.3  2.3889  1.0  273.0   
1008  393.45000   6.48  22.00  NaN     NaN     NaN    NaN     NaN  NaN    NaN   
1009    0.04741   0.00  11.93  0.0   0.573   6.030   80.8  2.5050  1.0  273.0   
1010  396.90000   7.88  11.90  NaN     NaN     NaN    NaN     NaN  NaN    NaN   

      15.30  
0       NaN  

In [ ]:
pf=pd.read_csv("/content/sample_data/california_housing_train.csv")
pf.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [ ]:
pf.shape

(17000, 9)

In [ ]:
diabetes=pd.read_csv('/diabetes.csv')
diabetes.head()

FileNotFoundError: [Errno 2] No such file or directory: '/diabetes.csv'

In [ ]:
type(diabetes)

In [ ]:
diabetes.shape

In [ ]:
diabetes.to_csv('prince.csv')

In [ ]:
cf=pd.read_csv('/content/sample_data/mnist_test.csv')
cf.head()

In [ ]:
diabetes.info()

In [ ]:
diabetes.isnull().sum()

In [ ]:
diabetes.value_counts('Outcome')

In [ ]:
diabetes.value_counts('Age')

In [ ]:
 diabetes.groupby('Outcome').mean()

In [ ]:
diabetes.describe()

In [ ]:
# matplotlib

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x=np.linspace(0,10,100)
y=np.sin(x)
z=np.cos(x)
print(x)

In [ ]:
plt.plot(x,y)
plt.show()

In [ ]:
plt.plot(x,z)
plt.show()

Importing data from kaggle using api


In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

Importing the earthquake Dataset


In [ ]:
!kaggle competitions download -c LANL-Earthquake-Prediction

100% 2.27G/2.27G [00:37<00:00, 31.5MB/s]
100% 2.27G/2.27G [00:37<00:00, 64.3MB/s]


In [ ]:
!kaggle competitions download -c LANL-Earthquake-Prediction

LANL-Earthquake-Prediction.zip: Skipping, found more recently modified local copy (use --force to force download)


In [ ]:
from zipfile import ZipFile
dataset='/content/LANL-Earthquake-Prediction.zip'
with ZipFile(dataset,'r') as zip:
  zip.extractall()
  print('The dataset is extracted')

The dataset is extracted
